image:
    file: .gitpod.dockerfile

tasks:
    - init: npm install
    - command: mkdir -p /workspace/data && mongod --dbpath /workspace/data
    - command: eval $(gp env -e)
    - command: npm i -g nodemon
